name: Build Jekyll Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Build the Jekyll site
      - name: Build site
        run: bundle exec jekyll build

      # Upload the generated site (_site folder) as an artifact
      - name: Upload built site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: clugston-joshua-github-io
          directory: _site
          branch: master
